
services:
    nami_contact_form.type.contact:
        class: PhpInk\Nami\ContactFormBundle\Form\Type\ContactType
        arguments:
            - "@translator"
        tags:
            - { name: form.type }

    nami_contact_form.type.captchaform:
        class: PhpInk\Nami\ContactFormBundle\Form\Type\CaptchaType
        arguments:
            - "@translator"
        tags:
            - { name: form.type }

    # BlockRenderEvent listener
    nami_contact_form.listener:
        class: PhpInk\Nami\ContactFormBundle\EventListener\BlockRenderListener
        arguments:
            - "%nami_contact_form.mail_to%"
            - "%host%"
            - "@form.factory"
            - "@translator"
            - "@twig"
            - "@mailer"
        tags:
            - { name: kernel.event_listener, event: nami.block.render, method: onBlockRender }
